services:
  postgres:
    build:
      context: ./docker/postgres
    restart: always
    environment:
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
    ports:
      - "54321:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres/data/:/var/lib/postgresql/data/
  php-fpm:
    container_name: levart-php
    # build:
    #   context: ./docker/php-fpm
    image: levart-api:latest
    restart: always
    # environment:
    #   - APP_ENV=${APP_ENV}
    #   - APP_SECRET=${APP_SECRET}
    #   - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - .:/var/www/
      - ./docker/supervisor/conf/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./docker/supervisor/conf/supervisord-programs.conf:/etc/supervisor/conf.d/app.conf
    # command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  nginx:
    container_name: levart-nginx
    build:
      context: ./docker/nginx
    restart: always
    volumes:
      - .:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      # - ./docker/nginx/logs:/var/log/
    depends_on:
      - php-fpm
      # - mysql
      # - postgres
    ports:
      - "8081:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # supervisor:
  #   container_name: levart-supervisor
  #   build: 
  #     context: ./docker/supervisor
  #   volumes:
  #     - .:/var/www/
  #     - ./docker/supervisor/conf/supervisord.conf:/etc/supervisor/supervisord.conf
  #     - ./docker/supervisor/conf/supervisord-programs.conf:/etc/supervisor/conf.d/app.conf
  #   command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
  #   depends_on:
  #     - php-fpm
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

