FROM nginx:1.18

# RUN mkdir /var/log/nginx
# RUN touch /var/log/nginx/error.log
# RUN touch /var/log/nginx/access.log
# RUN chown -R www-data:www-data /var/log

WORKDIR /var/www

EXPOSE 80
CMD ["nginx"]